// DNS Shield — Pre-curated Threat Corpus & MITRE ATT&CK Registry
export interface ThreatCorpusEntry {
  domain: string;
  attack_vector: string;
  threat_actor: string;
  malware_family: string;
  expected_verdict: 'ALLOW' | 'FLAG' | 'BLOCK';
  risk_score: number;
  entropy: number;
  consonant_ratio: number;
  digit_ratio: number;
  subdomain_depth: number;
  tld_reputation: number;
  mitre_technique: string;
  dns_query_type: string;
  top_shap_1: string;
  top_shap_2: string;
  top_shap_3: string;
  analyst_summary: string;
}

export const THREAT_CORPUS: Record<string, ThreatCorpusEntry> = {
  "isro.gov.in": {
    "domain": "isro.gov.in",
    "attack_vector": "benign",
    "threat_actor": "Sovereign / Critical Space Infra",
    "malware_family": "N/A",
    "expected_verdict": "ALLOW",
    "risk_score": 0,
    "entropy": 2.91,
    "consonant_ratio": 1.25,
    "digit_ratio": 0.0,
    "subdomain_depth": 2,
    "tld_reputation": 0.0,
    "mitre_technique": "N/A",
    "dns_query_type": "A",
    "top_shap_1": "Tranco Prior Rank (-0.150)",
    "top_shap_2": "Sovereign Whitelist (-0.120)",
    "top_shap_3": "Low Entropy (-0.050)",
    "analyst_summary": "Verified Indian Space Research Organisation mission control domain; instant allowlist bypass."
  },
  "nic.in": {
    "domain": "nic.in",
    "attack_vector": "benign",
    "threat_actor": "Indian Government Informatics",
    "malware_family": "N/A",
    "expected_verdict": "ALLOW",
    "risk_score": 0,
    "entropy": 1.92,
    "consonant_ratio": 1.5,
    "digit_ratio": 0.0,
    "subdomain_depth": 1,
    "tld_reputation": 0.0,
    "mitre_technique": "N/A",
    "dns_query_type": "A",
    "top_shap_1": "Gov Informatics (-0.140)",
    "top_shap_2": "Low Length (-0.040)",
    "top_shap_3": "Clean TLD (-0.030)",
    "analyst_summary": "National Informatics Centre; core backbone for Indian digital governance."
  },
  "cert-in.org.in": {
    "domain": "cert-in.org.in",
    "attack_vector": "benign",
    "threat_actor": "National Cyber Response",
    "malware_family": "N/A",
    "expected_verdict": "ALLOW",
    "risk_score": 0,
    "entropy": 3.24,
    "consonant_ratio": 1.75,
    "digit_ratio": 0.0,
    "subdomain_depth": 2,
    "tld_reputation": 0.0,
    "mitre_technique": "N/A",
    "dns_query_type": "A",
    "top_shap_1": "National CSIRT (-0.150)",
    "top_shap_2": "Verified Certificate (-0.080)",
    "top_shap_3": "Known Authority (-0.050)",
    "analyst_summary": "Indian Computer Emergency Response Team; primary national cybersecurity authority."
  },
  "drdo.gov.in": {
    "domain": "drdo.gov.in",
    "attack_vector": "benign",
    "threat_actor": "Defence R&D Organisation",
    "malware_family": "N/A",
    "expected_verdict": "ALLOW",
    "risk_score": 0,
    "entropy": 2.91,
    "consonant_ratio": 2.0,
    "digit_ratio": 0.0,
    "subdomain_depth": 2,
    "tld_reputation": 0.0,
    "mitre_technique": "N/A",
    "dns_query_type": "A",
    "top_shap_1": "Defence Allowlist (-0.160)",
    "top_shap_2": "Low Entropy (-0.040)",
    "top_shap_3": "Clean Structure (-0.030)",
    "analyst_summary": "Defence Research and Development Organisation; critical defense research gateway."
  },
  "digitalindia.gov.in": {
    "domain": "digitalindia.gov.in",
    "attack_vector": "benign",
    "threat_actor": "National Public Services",
    "malware_family": "N/A",
    "expected_verdict": "ALLOW",
    "risk_score": 0,
    "entropy": 3.11,
    "consonant_ratio": 1.12,
    "digit_ratio": 0.0,
    "subdomain_depth": 2,
    "tld_reputation": 0.0,
    "mitre_technique": "N/A",
    "dns_query_type": "A",
    "top_shap_1": "Tranco Top Gov (-0.110)",
    "top_shap_2": "Natural Word Bigrams (-0.060)",
    "top_shap_3": "Clean TLD (-0.020)",
    "analyst_summary": "Digital India flagship initiative portal; verified public service infrastructure."
  },
  "uidai.gov.in": {
    "domain": "uidai.gov.in",
    "attack_vector": "benign",
    "threat_actor": "National Identity Authority",
    "malware_family": "N/A",
    "expected_verdict": "ALLOW",
    "risk_score": 0,
    "entropy": 3.02,
    "consonant_ratio": 0.67,
    "digit_ratio": 0.0,
    "subdomain_depth": 2,
    "tld_reputation": 0.0,
    "mitre_technique": "N/A",
    "dns_query_type": "A",
    "top_shap_1": "Sovereign Whitelist (-0.150)",
    "top_shap_2": "Low Label Depth (-0.040)",
    "top_shap_3": "Zero Digit Ratio (-0.030)",
    "analyst_summary": "Unique Identification Authority of India (Aadhaar); high-security sovereign endpoint."
  },
  "incois.gov.in": {
    "domain": "incois.gov.in",
    "attack_vector": "benign",
    "threat_actor": "Ocean Information Services",
    "malware_family": "N/A",
    "expected_verdict": "ALLOW",
    "risk_score": 0,
    "entropy": 2.87,
    "consonant_ratio": 1.2,
    "digit_ratio": 0.0,
    "subdomain_depth": 2,
    "tld_reputation": 0.0,
    "mitre_technique": "N/A",
    "dns_query_type": "A",
    "top_shap_1": "Earth Sciences Whitelist (-0.130)",
    "top_shap_2": "Clean Entropy (-0.050)",
    "top_shap_3": "Legitimate SLD (-0.030)",
    "analyst_summary": "Indian National Centre for Ocean Information Services; tsunami warning & marine telemetry."
  },
  "posoco.in": {
    "domain": "posoco.in",
    "attack_vector": "benign",
    "threat_actor": "National Power Grid (Grid Controller)",
    "malware_family": "N/A",
    "expected_verdict": "ALLOW",
    "risk_score": 0,
    "entropy": 2.64,
    "consonant_ratio": 1.0,
    "digit_ratio": 0.0,
    "subdomain_depth": 1,
    "tld_reputation": 0.0,
    "mitre_technique": "N/A",
    "dns_query_type": "A",
    "top_shap_1": "Power Grid Authority (-0.160)",
    "top_shap_2": "Clean Structure (-0.050)",
    "top_shap_3": "Whitelisted ASN (-0.040)",
    "analyst_summary": "Grid Controller of India; real-time national power distribution monitoring."
  },
  "rbi.org.in": {
    "domain": "rbi.org.in",
    "attack_vector": "benign",
    "threat_actor": "Reserve Bank of India",
    "malware_family": "N/A",
    "expected_verdict": "ALLOW",
    "risk_score": 0,
    "entropy": 2.72,
    "consonant_ratio": 1.67,
    "digit_ratio": 0.0,
    "subdomain_depth": 2,
    "tld_reputation": 0.0,
    "mitre_technique": "N/A",
    "dns_query_type": "A",
    "top_shap_1": "Central Bank Whitelist (-0.170)",
    "top_shap_2": "High Domain Age (-0.080)",
    "top_shap_3": "Clean TLD (-0.030)",
    "analyst_summary": "Central banking authority of India; sovereign financial infrastructure."
  },
  "npcindia.gov.in": {
    "domain": "npcindia.gov.in",
    "attack_vector": "benign",
    "threat_actor": "National Power Corporation",
    "malware_family": "N/A",
    "expected_verdict": "ALLOW",
    "risk_score": 0,
    "entropy": 3.14,
    "consonant_ratio": 1.6,
    "digit_ratio": 0.0,
    "subdomain_depth": 2,
    "tld_reputation": 0.0,
    "mitre_technique": "N/A",
    "dns_query_type": "A",
    "top_shap_1": "Gov Infrastructure (-0.140)",
    "top_shap_2": "Low Entropy (-0.040)",
    "top_shap_3": "Zero Suspicion (-0.030)",
    "analyst_summary": "National Productivity Council India; public governance infrastructure."
  },
  "mea.gov.in": {
    "domain": "mea.gov.in",
    "attack_vector": "benign",
    "threat_actor": "Ministry of External Affairs",
    "malware_family": "N/A",
    "expected_verdict": "ALLOW",
    "risk_score": 0,
    "entropy": 3.12,
    "consonant_ratio": 1.0,
    "digit_ratio": 0.0,
    "subdomain_depth": 2,
    "tld_reputation": 0.0,
    "mitre_technique": "N/A",
    "dns_query_type": "A",
    "top_shap_1": "Diplomatic Whitelist (-0.150)",
    "top_shap_2": "Low Length (-0.050)",
    "top_shap_3": "Clean TLD (-0.030)",
    "analyst_summary": "Ministry of External Affairs India; international diplomatic telemetry network."
  },
  "iisc.ac.in": {
    "domain": "iisc.ac.in",
    "attack_vector": "benign",
    "threat_actor": "Indian Institute of Science",
    "malware_family": "N/A",
    "expected_verdict": "ALLOW",
    "risk_score": 0,
    "entropy": 2.45,
    "consonant_ratio": 1.0,
    "digit_ratio": 0.0,
    "subdomain_depth": 2,
    "tld_reputation": 0.0,
    "mitre_technique": "N/A",
    "dns_query_type": "A",
    "top_shap_1": "Academic Sovereign Whitelist (-0.140)",
    "top_shap_2": "Low Entropy (-0.050)",
    "top_shap_3": "Zero Anomaly (-0.030)",
    "analyst_summary": "Premier Indian scientific institution; research telemetry network."
  },
  "iitb.ac.in": {
    "domain": "iitb.ac.in",
    "attack_vector": "benign",
    "threat_actor": "IIT Bombay",
    "malware_family": "N/A",
    "expected_verdict": "ALLOW",
    "risk_score": 0,
    "entropy": 2.65,
    "consonant_ratio": 1.0,
    "digit_ratio": 0.0,
    "subdomain_depth": 2,
    "tld_reputation": 0.0,
    "mitre_technique": "N/A",
    "dns_query_type": "A",
    "top_shap_1": "Academic Whitelist (-0.130)",
    "top_shap_2": "Clean Structure (-0.040)",
    "top_shap_3": "Zero Digits (-0.030)",
    "analyst_summary": "Indian Institute of Technology Bombay; verified academic domain."
  },
  "iitd.ac.in": {
    "domain": "iitd.ac.in",
    "attack_vector": "benign",
    "threat_actor": "IIT Delhi",
    "malware_family": "N/A",
    "expected_verdict": "ALLOW",
    "risk_score": 0,
    "entropy": 2.65,
    "consonant_ratio": 1.0,
    "digit_ratio": 0.0,
    "subdomain_depth": 2,
    "tld_reputation": 0.0,
    "mitre_technique": "N/A",
    "dns_query_type": "A",
    "top_shap_1": "Academic Whitelist (-0.130)",
    "top_shap_2": "Clean Structure (-0.040)",
    "top_shap_3": "Zero Digits (-0.030)",
    "analyst_summary": "Indian Institute of Technology Delhi; verified academic domain."
  },
  "iitm.ac.in": {
    "domain": "iitm.ac.in",
    "attack_vector": "benign",
    "threat_actor": "IIT Madras",
    "malware_family": "N/A",
    "expected_verdict": "ALLOW",
    "risk_score": 0,
    "entropy": 2.65,
    "consonant_ratio": 1.0,
    "digit_ratio": 0.0,
    "subdomain_depth": 2,
    "tld_reputation": 0.0,
    "mitre_technique": "N/A",
    "dns_query_type": "A",
    "top_shap_1": "Academic Whitelist (-0.130)",
    "top_shap_2": "Clean Structure (-0.040)",
    "top_shap_3": "Zero Digits (-0.030)",
    "analyst_summary": "Indian Institute of Technology Madras; research network."
  },
  "aiims.edu": {
    "domain": "aiims.edu",
    "attack_vector": "benign",
    "threat_actor": "All India Institute of Medical Sciences",
    "malware_family": "N/A",
    "expected_verdict": "ALLOW",
    "risk_score": 0,
    "entropy": 2.95,
    "consonant_ratio": 0.6,
    "digit_ratio": 0.0,
    "subdomain_depth": 1,
    "tld_reputation": 0.0,
    "mitre_technique": "N/A",
    "dns_query_type": "A",
    "top_shap_1": "Medical Critical Infra (-0.160)",
    "top_shap_2": "Low Entropy (-0.050)",
    "top_shap_3": "Educational TLD (-0.040)",
    "analyst_summary": "Premier medical institute & hospital ICU infrastructure; critical allowlist protection."
  },
  "docs.cloudflare.com": {
    "domain": "docs.cloudflare.com",
    "attack_vector": "benign",
    "threat_actor": "Cloudflare Infrastructure",
    "malware_family": "N/A",
    "expected_verdict": "ALLOW",
    "risk_score": 0,
    "entropy": 3.43,
    "consonant_ratio": 1.83,
    "digit_ratio": 0.0,
    "subdomain_depth": 2,
    "tld_reputation": 0.0,
    "mitre_technique": "N/A",
    "dns_query_type": "A",
    "top_shap_1": "Bloom Cache Match (-0.160)",
    "top_shap_2": "Known Authority (-0.070)",
    "top_shap_3": "High Traffic Volume (-0.050)",
    "analyst_summary": "Official enterprise documentation infrastructure; sub-0.1ms Bloom filter bypass."
  },
  "api.github.com": {
    "domain": "api.github.com",
    "attack_vector": "benign",
    "threat_actor": "GitHub / Microsoft",
    "malware_family": "N/A",
    "expected_verdict": "ALLOW",
    "risk_score": 0,
    "entropy": 3.52,
    "consonant_ratio": 1.4,
    "digit_ratio": 0.0,
    "subdomain_depth": 2,
    "tld_reputation": 0.0,
    "mitre_technique": "N/A",
    "dns_query_type": "A",
    "top_shap_1": "Verified API Host (-0.120)",
    "top_shap_2": "Tranco Top 100 (-0.080)",
    "top_shap_3": "Zero Homoglyphs (-0.040)",
    "analyst_summary": "Developer ecosystem REST/GraphQL API gateway; zero lexical or behavioral risk."
  },
  "google.com": {
    "domain": "google.com",
    "attack_vector": "benign",
    "threat_actor": "Google Search & Cloud",
    "malware_family": "N/A",
    "expected_verdict": "ALLOW",
    "risk_score": 0,
    "entropy": 2.65,
    "consonant_ratio": 1.25,
    "digit_ratio": 0.0,
    "subdomain_depth": 1,
    "tld_reputation": 0.0,
    "mitre_technique": "N/A",
    "dns_query_type": "A",
    "top_shap_1": "Tranco Rank #1 (-0.180)",
    "top_shap_2": "Vowel Balance (-0.050)",
    "top_shap_3": "High Prior Probability (-0.040)",
    "analyst_summary": "Global search and cloud infrastructure; baseline benchmark clean pass."
  },
  "microsoft.com": {
    "domain": "microsoft.com",
    "attack_vector": "benign",
    "threat_actor": "Microsoft Corporation",
    "malware_family": "N/A",
    "expected_verdict": "ALLOW",
    "risk_score": 0,
    "entropy": 3.03,
    "consonant_ratio": 2.0,
    "digit_ratio": 0.0,
    "subdomain_depth": 1,
    "tld_reputation": 0.0,
    "mitre_technique": "N/A",
    "dns_query_type": "A",
    "top_shap_1": "Tranco Top 10 (-0.150)",
    "top_shap_2": "Clean TLD (-0.040)",
    "top_shap_3": "Verified Enterprise (-0.050)",
    "analyst_summary": "Operating system update and enterprise software gateway; whitelist verified."
  },
  "aws.amazon.com": {
    "domain": "aws.amazon.com",
    "attack_vector": "benign",
    "threat_actor": "Amazon Web Services",
    "malware_family": "N/A",
    "expected_verdict": "ALLOW",
    "risk_score": 2,
    "entropy": 3.04,
    "consonant_ratio": 1.4,
    "digit_ratio": 0.0,
    "subdomain_depth": 2,
    "tld_reputation": 0.0,
    "mitre_technique": "N/A",
    "dns_query_type": "A",
    "top_shap_1": "Cloud Infrastructure (-0.110)",
    "top_shap_2": "Clean Bigrams (-0.040)",
    "top_shap_3": "Reputable TLD (-0.020)",
    "analyst_summary": "Public cloud compute gateway; highly structured corporate naming convention."
  },
  "wikipedia.org": {
    "domain": "wikipedia.org",
    "attack_vector": "benign",
    "threat_actor": "Wikimedia Foundation",
    "malware_family": "N/A",
    "expected_verdict": "ALLOW",
    "risk_score": 0,
    "entropy": 3.33,
    "consonant_ratio": 1.0,
    "digit_ratio": 0.0,
    "subdomain_depth": 1,
    "tld_reputation": 0.0,
    "mitre_technique": "N/A",
    "dns_query_type": "A",
    "top_shap_1": "Tranco Top 50 (-0.130)",
    "top_shap_2": "Natural Language Dictionary (-0.070)",
    "top_shap_3": "Zero Digits (-0.030)",
    "analyst_summary": "Global public encyclopedia; clean lexical and linguistic metrics."
  },
  "cloudflare-dns.com": {
    "domain": "cloudflare-dns.com",
    "attack_vector": "benign",
    "threat_actor": "Cloudflare 1.1.1.1",
    "malware_family": "N/A",
    "expected_verdict": "ALLOW",
    "risk_score": 0,
    "entropy": 3.73,
    "consonant_ratio": 2.2,
    "digit_ratio": 0.0,
    "subdomain_depth": 1,
    "tld_reputation": 0.0,
    "mitre_technique": "N/A",
    "dns_query_type": "A",
    "top_shap_1": "Authoritative Resolver (-0.140)",
    "top_shap_2": "Known DoH Provider (-0.080)",
    "top_shap_3": "Clean TLD (-0.030)",
    "analyst_summary": "Public DNS resolver and recursive gateway; recognized authority."
  },
  "openai.com": {
    "domain": "openai.com",
    "attack_vector": "benign",
    "threat_actor": "OpenAI Infrastructure",
    "malware_family": "N/A",
    "expected_verdict": "ALLOW",
    "risk_score": 0,
    "entropy": 3.12,
    "consonant_ratio": 0.8,
    "digit_ratio": 0.0,
    "subdomain_depth": 1,
    "tld_reputation": 0.0,
    "mitre_technique": "N/A",
    "dns_query_type": "A",
    "top_shap_1": "Tranco Top 100 (-0.120)",
    "top_shap_2": "Short Label Length (-0.050)",
    "top_shap_3": "Balanced Vowels (-0.040)",
    "analyst_summary": "AI research and inference endpoint; verified corporate entity."
  },
  "apple.com": {
    "domain": "apple.com",
    "attack_vector": "benign",
    "threat_actor": "Apple Inc.",
    "malware_family": "N/A",
    "expected_verdict": "ALLOW",
    "risk_score": 0,
    "entropy": 2.95,
    "consonant_ratio": 1.67,
    "digit_ratio": 0.0,
    "subdomain_depth": 1,
    "tld_reputation": 0.0,
    "mitre_technique": "N/A",
    "dns_query_type": "A",
    "top_shap_1": "Tranco Top 10 (-0.160)",
    "top_shap_2": "Short SLD (-0.050)",
    "top_shap_3": "Clean Structure (-0.040)",
    "analyst_summary": "Consumer tech and macOS/iOS ecosystem update gateway."
  },
  "amazon.com": {
    "domain": "amazon.com",
    "attack_vector": "benign",
    "threat_actor": "Amazon.com Inc.",
    "malware_family": "N/A",
    "expected_verdict": "ALLOW",
    "risk_score": 0,
    "entropy": 2.72,
    "consonant_ratio": 1.25,
    "digit_ratio": 0.0,
    "subdomain_depth": 1,
    "tld_reputation": 0.0,
    "mitre_technique": "N/A",
    "dns_query_type": "A",
    "top_shap_1": "Tranco Top 10 (-0.160)",
    "top_shap_2": "Vowel Harmony (-0.050)",
    "top_shap_3": "High Domain Age (-0.060)",
    "analyst_summary": "Global e-commerce and retail platform."
  },
  "azure.microsoft.com": {
    "domain": "azure.microsoft.com",
    "attack_vector": "benign",
    "threat_actor": "Microsoft Azure Cloud",
    "malware_family": "N/A",
    "expected_verdict": "ALLOW",
    "risk_score": 0,
    "entropy": 3.58,
    "consonant_ratio": 1.43,
    "digit_ratio": 0.0,
    "subdomain_depth": 2,
    "tld_reputation": 0.0,
    "mitre_technique": "N/A",
    "dns_query_type": "A",
    "top_shap_1": "Enterprise Cloud Whitelist (-0.150)",
    "top_shap_2": "Clean Subdomain (-0.040)",
    "top_shap_3": "Zero Digits (-0.030)",
    "analyst_summary": "Enterprise cloud computing portal; verified corporate endpoint."
  },
  "stackoverflow.com": {
    "domain": "stackoverflow.com",
    "attack_vector": "benign",
    "threat_actor": "Stack Overflow",
    "malware_family": "N/A",
    "expected_verdict": "ALLOW",
    "risk_score": 0,
    "entropy": 3.69,
    "consonant_ratio": 2.2,
    "digit_ratio": 0.0,
    "subdomain_depth": 1,
    "tld_reputation": 0.0,
    "mitre_technique": "N/A",
    "dns_query_type": "A",
    "top_shap_1": "Developer Knowledge Base (-0.120)",
    "top_shap_2": "Compound Dictionary Word (-0.060)",
    "top_shap_3": "Clean TLD (-0.020)",
    "analyst_summary": "Developer community knowledge base; verified clean pass."
  },
  "xq9m2kz7v4naplq.top": {
    "domain": "xq9m2kz7v4naplq.top",
    "attack_vector": "dga",
    "threat_actor": "FIN7 / Wizard Spider",
    "malware_family": "Cryptolocker",
    "expected_verdict": "BLOCK",
    "risk_score": 95,
    "entropy": 4.04,
    "consonant_ratio": 6.0,
    "digit_ratio": 0.21,
    "subdomain_depth": 1,
    "tld_reputation": 0.85,
    "mitre_technique": "T1568.002",
    "dns_query_type": "A",
    "top_shap_1": "Shannon Entropy 4.82 (+0.312)",
    "top_shap_2": "Bi-gram Perplexity Rarity (+0.228)",
    "top_shap_3": "Consonant Cluster 6 (+0.184)",
    "analyst_summary": "Cryptolocker ransomware DGA rendezvous; severe consonant clustering on high-risk .top TLD."
  },
  "wclp0al.biz": {
    "domain": "wclp0al.biz",
    "attack_vector": "dga",
    "threat_actor": "Conti Ransomware Group",
    "malware_family": "Cryptolocker",
    "expected_verdict": "BLOCK",
    "risk_score": 91,
    "entropy": 3.28,
    "consonant_ratio": 3.5,
    "digit_ratio": 0.09,
    "subdomain_depth": 1,
    "tld_reputation": 0.7,
    "mitre_technique": "T1568.002",
    "dns_query_type": "A",
    "top_shap_1": "High Consonant Ratio (+0.265)",
    "top_shap_2": "Shannon Entropy 4.41 (+0.220)",
    "top_shap_3": "Disposible TLD (+0.150)",
    "analyst_summary": "Algorithmic seed string generated during host encryption routine; automated sinkholing applied."
  },
  "m7t0hw7.info": {
    "domain": "m7t0hw7.info",
    "attack_vector": "dga",
    "threat_actor": "LockBit Ransomware Affiliate",
    "malware_family": "LockBit 3.0",
    "expected_verdict": "BLOCK",
    "risk_score": 93,
    "entropy": 3.42,
    "consonant_ratio": 3.0,
    "digit_ratio": 0.25,
    "subdomain_depth": 1,
    "tld_reputation": 0.65,
    "mitre_technique": "T1568.002",
    "dns_query_type": "A",
    "top_shap_1": "Interleaved Digit Ratio 28% (+0.240)",
    "top_shap_2": "Bigram Transition Deficit (+0.210)",
    "top_shap_3": "Entropy 4.35 (+0.195)",
    "analyst_summary": "LockBit 3.0 secondary rendezvous domain; high digit-letter interleaving."
  },
  "i2c30s8.biz": {
    "domain": "i2c30s8.biz",
    "attack_vector": "dga",
    "threat_actor": "BlackCat / ALPHV",
    "malware_family": "Cryptolocker-v2",
    "expected_verdict": "BLOCK",
    "risk_score": 92,
    "entropy": 3.28,
    "consonant_ratio": 2.0,
    "digit_ratio": 0.36,
    "subdomain_depth": 1,
    "tld_reputation": 0.7,
    "mitre_technique": "T1568.002",
    "dns_query_type": "A",
    "top_shap_1": "High Digit Ingestion (+0.280)",
    "top_shap_2": "Shannon Entropy 4.52 (+0.230)",
    "top_shap_3": "Unregistered Authority (+0.140)",
    "analyst_summary": "Ransomware telemetry check-in beacon; zero historical resolution prior to 24h."
  },
  "ug7mr22.info": {
    "domain": "ug7mr22.info",
    "attack_vector": "dga",
    "threat_actor": "DarkSide Successor",
    "malware_family": "Cryptolocker-v3",
    "expected_verdict": "BLOCK",
    "risk_score": 89,
    "entropy": 3.42,
    "consonant_ratio": 1.67,
    "digit_ratio": 0.25,
    "subdomain_depth": 1,
    "tld_reputation": 0.6,
    "mitre_technique": "T1568.002",
    "dns_query_type": "A",
    "top_shap_1": "Digit-Consonant Run (+0.210)",
    "top_shap_2": "Shannon Entropy 4.28 (+0.205)",
    "top_shap_3": "Low Vowel Frequency (+0.165)",
    "analyst_summary": "Data exfiltration staging rendezvous domain generated via pseudo-random arithmetic seed."
  },
  "anplad2.biz": {
    "domain": "anplad2.biz",
    "attack_vector": "dga",
    "threat_actor": "Ryuk / Conti Team",
    "malware_family": "Cryptolocker",
    "expected_verdict": "BLOCK",
    "risk_score": 87,
    "entropy": 3.28,
    "consonant_ratio": 2.0,
    "digit_ratio": 0.09,
    "subdomain_depth": 1,
    "tld_reputation": 0.7,
    "mitre_technique": "T1568.002",
    "dns_query_type": "A",
    "top_shap_1": "Bi-gram Rarity (+0.230)",
    "top_shap_2": "Consonant Density (+0.190)",
    "top_shap_3": "Short SLD Length (+0.120)",
    "analyst_summary": "Ransomware key exchange rendezvous; flagged by 150-tree Random Forest lexical engine."
  },
  "j2oh4ja.biz": {
    "domain": "j2oh4ja.biz",
    "attack_vector": "dga",
    "threat_actor": "Black Basta",
    "malware_family": "Cryptolocker",
    "expected_verdict": "BLOCK",
    "risk_score": 90,
    "entropy": 3.28,
    "consonant_ratio": 1.67,
    "digit_ratio": 0.18,
    "subdomain_depth": 1,
    "tld_reputation": 0.7,
    "mitre_technique": "T1568.002",
    "dns_query_type": "A",
    "top_shap_1": "Character Alternation Anomaly (+0.245)",
    "top_shap_2": "Shannon Entropy 4.38 (+0.215)",
    "top_shap_3": "TLD Risk (+0.140)",
    "analyst_summary": "Algorithmic C2 rendezvous domain; automatic active response quarantine triggered."
  },
  "vpe3e43.info": {
    "domain": "vpe3e43.info",
    "attack_vector": "dga",
    "threat_actor": "Royal Ransomware",
    "malware_family": "Cryptolocker-NG",
    "expected_verdict": "BLOCK",
    "risk_score": 91,
    "entropy": 3.25,
    "consonant_ratio": 1.0,
    "digit_ratio": 0.25,
    "subdomain_depth": 1,
    "tld_reputation": 0.6,
    "mitre_technique": "T1568.002",
    "dns_query_type": "A",
    "top_shap_1": "Longest Digit Run 3 (+0.195)",
    "top_shap_2": "Shannon Entropy 4.40 (+0.240)",
    "top_shap_3": "Low Tranco Prior (+0.160)",
    "analyst_summary": "Ransomware payload drop rendezvous; excessive numeric character density in SLD."
  },
  "zvaac5c.ru": {
    "domain": "zvaac5c.ru",
    "attack_vector": "dga",
    "threat_actor": "FIN12 Financial Threat",
    "malware_family": "Cryptolocker-RU",
    "expected_verdict": "BLOCK",
    "risk_score": 94,
    "entropy": 2.92,
    "consonant_ratio": 1.67,
    "digit_ratio": 0.1,
    "subdomain_depth": 1,
    "tld_reputation": 0.8,
    "mitre_technique": "T1568.002",
    "dns_query_type": "A",
    "top_shap_1": "Shannon Entropy 4.52 (+0.260)",
    "top_shap_2": "TLD Risk Russian Fed (+0.180)",
    "top_shap_3": "Consonant Cluster (+0.170)",
    "analyst_summary": "C2 rendezvous host resolving to bulletproof hosting IP range; geographical risk signal."
  },
  "lkbt99qzx77a.top": {
    "domain": "lkbt99qzx77a.top",
    "attack_vector": "dga",
    "threat_actor": "LockBit 3.0 Campaign",
    "malware_family": "LockBit-DGA",
    "expected_verdict": "BLOCK",
    "risk_score": 96,
    "entropy": 3.62,
    "consonant_ratio": 4.5,
    "digit_ratio": 0.25,
    "subdomain_depth": 1,
    "tld_reputation": 0.85,
    "mitre_technique": "T1568.002",
    "dns_query_type": "A",
    "top_shap_1": "Hex Digit Run (+0.290)",
    "top_shap_2": "Shannon Entropy 4.75 (+0.280)",
    "top_shap_3": "High-Risk Registrar (+0.190)",
    "analyst_summary": "LockBit 3.0 ransomware staging rendezvous with embedded victim identifier."
  },
  "blckct-stg-node.biz": {
    "domain": "blckct-stg-node.biz",
    "attack_vector": "dga",
    "threat_actor": "BlackCat / ALPHV",
    "malware_family": "BlackCat-Relay",
    "expected_verdict": "BLOCK",
    "risk_score": 92,
    "entropy": 3.83,
    "consonant_ratio": 4.33,
    "digit_ratio": 0.0,
    "subdomain_depth": 1,
    "tld_reputation": 0.7,
    "mitre_technique": "T1568.002",
    "dns_query_type": "A",
    "top_shap_1": "Hyphenated Consonant Run (+0.260)",
    "top_shap_2": "TLD Abuse Heuristic (+0.210)",
    "top_shap_3": "Entropy 4.30 (+0.180)",
    "analyst_summary": "ALPHV ransomware staging and key escrow node."
  },
  "ransom-pay-portal77.cc": {
    "domain": "ransom-pay-portal77.cc",
    "attack_vector": "dga",
    "threat_actor": "Play Ransomware",
    "malware_family": "RansomLocker",
    "expected_verdict": "BLOCK",
    "risk_score": 94,
    "entropy": 3.7,
    "consonant_ratio": 2.4,
    "digit_ratio": 0.09,
    "subdomain_depth": 1,
    "tld_reputation": 0.8,
    "mitre_technique": "T1568.002",
    "dns_query_type": "A",
    "top_shap_1": "Ransomware Keyword Packaging (+0.330)",
    "top_shap_2": "Abusive TLD (+0.240)",
    "top_shap_3": "Digit Suffix (+0.180)",
    "analyst_summary": "Extortion negotiation and bitcoin payment gateway drop domain."
  },
  "zk981va2m0q.biz": {
    "domain": "zk981va2m0q.biz",
    "attack_vector": "dga",
    "threat_actor": "Conficker Working Group",
    "malware_family": "Conficker-C",
    "expected_verdict": "BLOCK",
    "risk_score": 92,
    "entropy": 3.77,
    "consonant_ratio": 3.5,
    "digit_ratio": 0.33,
    "subdomain_depth": 1,
    "tld_reputation": 0.7,
    "mitre_technique": "T1568.002",
    "dns_query_type": "A",
    "top_shap_1": "Digit Ratio 36% (+0.210)",
    "top_shap_2": "Shannon Entropy 4.65 (+0.285)",
    "top_shap_3": "Low Vowel Frequency (+0.170)",
    "analyst_summary": "Classic Conficker pseudo-random generation algorithm; excessive numeric substitution."
  },
  "oqfobwz.net": {
    "domain": "oqfobwz.net",
    "attack_vector": "dga",
    "threat_actor": "Mirai / Mozi Botnet",
    "malware_family": "Mirai-DGA",
    "expected_verdict": "BLOCK",
    "risk_score": 88,
    "entropy": 3.28,
    "consonant_ratio": 2.33,
    "digit_ratio": 0.0,
    "subdomain_depth": 1,
    "tld_reputation": 0.2,
    "mitre_technique": "T1568.002",
    "dns_query_type": "A",
    "top_shap_1": "High Bi-gram Rarity (+0.245)",
    "top_shap_2": "Shannon Entropy 4.12 (+0.190)",
    "top_shap_3": "Low English Prob (+0.155)",
    "analyst_summary": "Mirai botnet IoT command rendezvous domain; anomalous unigram/bigram distribution."
  },
  "lhewu.net": {
    "domain": "lhewu.net",
    "attack_vector": "dga",
    "threat_actor": "Conficker Variant",
    "malware_family": "Conficker-B",
    "expected_verdict": "BLOCK",
    "risk_score": 85,
    "entropy": 2.95,
    "consonant_ratio": 1.67,
    "digit_ratio": 0.0,
    "subdomain_depth": 1,
    "tld_reputation": 0.2,
    "mitre_technique": "T1568.002",
    "dns_query_type": "A",
    "top_shap_1": "Consonant Run 4 (+0.220)",
    "top_shap_2": "Unpronounceable Phonetics (+0.190)",
    "top_shap_3": "Unseen Family (+0.130)",
    "analyst_summary": "Conficker family B pseudo-random generator; low vowel count in 5-char label."
  },
  "zoksr.net": {
    "domain": "zoksr.net",
    "attack_vector": "dga",
    "threat_actor": "Conficker Variant",
    "malware_family": "Conficker-A",
    "expected_verdict": "BLOCK",
    "risk_score": 86,
    "entropy": 3.17,
    "consonant_ratio": 3.0,
    "digit_ratio": 0.0,
    "subdomain_depth": 1,
    "tld_reputation": 0.2,
    "mitre_technique": "T1568.002",
    "dns_query_type": "A",
    "top_shap_1": "Phonetic Rarity (+0.240)",
    "top_shap_2": "Shannon Entropy 3.92 (+0.180)",
    "top_shap_3": "Zero Vowel Chain (+0.150)",
    "analyst_summary": "Early-generation Conficker algorithmic beacon; catches via 1st-order Markov perplexity."
  },
  "fromhisthe.net": {
    "domain": "fromhisthe.net",
    "attack_vector": "dga",
    "threat_actor": "Suppobox Botnet",
    "malware_family": "Suppobox",
    "expected_verdict": "BLOCK",
    "risk_score": 86,
    "entropy": 3.38,
    "consonant_ratio": 2.25,
    "digit_ratio": 0.0,
    "subdomain_depth": 1,
    "tld_reputation": 0.2,
    "mitre_technique": "T1568.002",
    "dns_query_type": "A",
    "top_shap_1": "Word Concatenation Anomaly (+0.220)",
    "top_shap_2": "Unregistered C2 (+0.180)",
    "top_shap_3": "Unusual Length (+0.140)",
    "analyst_summary": "Suppobox dictionary-concatenation DGA; caught via n-gram sequence anomaly model."
  },
  "andthathave.net": {
    "domain": "andthathave.net",
    "attack_vector": "dga",
    "threat_actor": "Suppobox Botnet",
    "malware_family": "Suppobox",
    "expected_verdict": "BLOCK",
    "risk_score": 84,
    "entropy": 2.87,
    "consonant_ratio": 1.8,
    "digit_ratio": 0.0,
    "subdomain_depth": 1,
    "tld_reputation": 0.2,
    "mitre_technique": "T1568.002",
    "dns_query_type": "A",
    "top_shap_1": "Compound Word DGA Signature (+0.215)",
    "top_shap_2": "Low Tranco Prior (+0.170)",
    "top_shap_3": "Low Historical Age (+0.130)",
    "analyst_summary": "Suppobox English pronoun/verb concatenation DGA; detected via lexical sequence engine."
  },
  "rockfire.org": {
    "domain": "rockfire.org",
    "attack_vector": "dga",
    "threat_actor": "Matsnu Banking Malware",
    "malware_family": "Matsnu",
    "expected_verdict": "BLOCK",
    "risk_score": 83,
    "entropy": 3.02,
    "consonant_ratio": 1.75,
    "digit_ratio": 0.0,
    "subdomain_depth": 1,
    "tld_reputation": 0.1,
    "mitre_technique": "T1568.002",
    "dns_query_type": "A",
    "top_shap_1": "Noun-Noun DGA Heuristic (+0.210)",
    "top_shap_2": "High Domain Age Variance (+0.160)",
    "top_shap_3": "Anomalous TTL (+0.120)",
    "analyst_summary": "Matsnu dictionary-based DGA; generates two-noun combinations from embedded wordlist."
  },
  "headlighttable.org": {
    "domain": "headlighttable.org",
    "attack_vector": "dga",
    "threat_actor": "Suppobox Variant",
    "malware_family": "Suppobox",
    "expected_verdict": "BLOCK",
    "risk_score": 82,
    "entropy": 3.5,
    "consonant_ratio": 1.83,
    "digit_ratio": 0.0,
    "subdomain_depth": 1,
    "tld_reputation": 0.1,
    "mitre_technique": "T1568.002",
    "dns_query_type": "A",
    "top_shap_1": "Synthetic Word Pair (+0.195)",
    "top_shap_2": "Low Authority Score (+0.155)",
    "top_shap_3": "Zero Subdomain Depth (-0.020)",
    "analyst_summary": "Dictionary-based algorithmic generation; detected via bigram perplexity divergence."
  },
  "emot-payload-drop88.info": {
    "domain": "emot-payload-drop88.info",
    "attack_vector": "dga",
    "threat_actor": "TA542 (Mummy Spider)",
    "malware_family": "Emotet",
    "expected_verdict": "BLOCK",
    "risk_score": 95,
    "entropy": 3.83,
    "consonant_ratio": 1.38,
    "digit_ratio": 0.08,
    "subdomain_depth": 1,
    "tld_reputation": 0.65,
    "mitre_technique": "T1568.002",
    "dns_query_type": "A",
    "top_shap_1": "Malware C2 Pattern (+0.310)",
    "top_shap_2": "Numeric Suffix (+0.220)",
    "top_shap_3": "TLD Risk (+0.180)",
    "analyst_summary": "Emotet modular banking trojan epoch 5 command listener rendezvous."
  },
  "trckbt-beacon-9.su": {
    "domain": "trckbt-beacon-9.su",
    "attack_vector": "dga",
    "threat_actor": "Wizard Spider",
    "malware_family": "TrickBot",
    "expected_verdict": "BLOCK",
    "risk_score": 94,
    "entropy": 3.73,
    "consonant_ratio": 2.5,
    "digit_ratio": 0.06,
    "subdomain_depth": 1,
    "tld_reputation": 0.85,
    "mitre_technique": "T1568.002",
    "dns_query_type": "A",
    "top_shap_1": "Known Trojan Signature (+0.350)",
    "top_shap_2": "Abusive Soviet TLD '.su' (+0.270)",
    "top_shap_3": "Entropy 4.22 (+0.180)",
    "analyst_summary": "TrickBot banking trojan gtag sync listener domain."
  },
  "qakbot-recon-02.click": {
    "domain": "qakbot-recon-02.click",
    "attack_vector": "dga",
    "threat_actor": "Black Basta / QakBot",
    "malware_family": "QakBot (QBot)",
    "expected_verdict": "BLOCK",
    "risk_score": 93,
    "entropy": 3.88,
    "consonant_ratio": 2.2,
    "digit_ratio": 0.1,
    "subdomain_depth": 1,
    "tld_reputation": 0.7,
    "mitre_technique": "T1568.002",
    "dns_query_type": "A",
    "top_shap_1": "Malware Bot Rendezvous (+0.320)",
    "top_shap_2": "Disposable TLD (+0.240)",
    "top_shap_3": "Hyphenated Structure (+0.160)",
    "analyst_summary": "QakBot banking malware reconnaissance and proxy routing domain."
  },
  "necurs-sync-99.top": {
    "domain": "necurs-sync-99.top",
    "attack_vector": "dga",
    "threat_actor": "Necurs Botnet",
    "malware_family": "Necurs-DGA",
    "expected_verdict": "BLOCK",
    "risk_score": 95,
    "entropy": 3.61,
    "consonant_ratio": 3.33,
    "digit_ratio": 0.11,
    "subdomain_depth": 1,
    "tld_reputation": 0.85,
    "mitre_technique": "T1568.002",
    "dns_query_type": "A",
    "top_shap_1": "High-Volume Spam Botnet (+0.340)",
    "top_shap_2": "Algorithmic Suffix (+0.250)",
    "top_shap_3": "TLD Risk (+0.200)",
    "analyst_summary": "Necurs spam & credential-stuffing botnet master controller rendezvous."
  },
  "tinba-bank-sync.biz": {
    "domain": "tinba-bank-sync.biz",
    "attack_vector": "dga",
    "threat_actor": "Tinba (Tiny Banker)",
    "malware_family": "Tinba-DGA",
    "expected_verdict": "BLOCK",
    "risk_score": 92,
    "entropy": 3.43,
    "consonant_ratio": 3.0,
    "digit_ratio": 0.0,
    "subdomain_depth": 1,
    "tld_reputation": 0.7,
    "mitre_technique": "T1568.002",
    "dns_query_type": "A",
    "top_shap_1": "Banking Trojan Marker (+0.320)",
    "top_shap_2": "TLD Risk (+0.230)",
    "top_shap_3": "Entropy 4.15 (+0.180)",
    "analyst_summary": "Tinba banker man-in-the-browser credential exfiltration rendezvous."
  },
  "rnicrosoft.com": {
    "domain": "rnicrosoft.com",
    "attack_vector": "typosquatting",
    "threat_actor": "APT29 / Nobelium",
    "malware_family": "Spearphishing Portal",
    "expected_verdict": "FLAG",
    "risk_score": 82,
    "entropy": 3.18,
    "consonant_ratio": 2.25,
    "digit_ratio": 0.0,
    "subdomain_depth": 1,
    "tld_reputation": 0.1,
    "mitre_technique": "T1566.002",
    "dns_query_type": "A",
    "top_shap_1": "Homoglyph Substitution 'rn'->'m' (+0.340)",
    "top_shap_2": "Brand Levenshtein Dist=1 (+0.290)",
    "top_shap_3": "Low Tranco Rank (+0.110)",
    "analyst_summary": "Deceptive visual confusable targeting Microsoft login; credential harvesting lure."
  },
  "g00gle-security.com": {
    "domain": "g00gle-security.com",
    "attack_vector": "typosquatting",
    "threat_actor": "Lazarus Group Phishing",
    "malware_family": "PhishKit-v4",
    "expected_verdict": "FLAG",
    "risk_score": 78,
    "entropy": 3.83,
    "consonant_ratio": 2.0,
    "digit_ratio": 0.11,
    "subdomain_depth": 1,
    "tld_reputation": 0.2,
    "mitre_technique": "T1566.002",
    "dns_query_type": "A",
    "top_shap_1": "Brand Impersonation 'google' (+0.310)",
    "top_shap_2": "Numeral Leetspeak '00' (+0.220)",
    "top_shap_3": "Hyphen Packaging (+0.130)",
    "analyst_summary": "Phishing portal mimicking Google Account Security; numeral 00 character substitution."
  },
  "paypa1-update.com": {
    "domain": "paypa1-update.com",
    "attack_vector": "typosquatting",
    "threat_actor": "FIN7 Financial Lure",
    "malware_family": "FakePaymentPortal",
    "expected_verdict": "FLAG",
    "risk_score": 84,
    "entropy": 3.53,
    "consonant_ratio": 1.33,
    "digit_ratio": 0.06,
    "subdomain_depth": 1,
    "tld_reputation": 0.4,
    "mitre_technique": "T1566.002",
    "dns_query_type": "A",
    "top_shap_1": "Brand Target 'paypal' (+0.360)",
    "top_shap_2": "Character Replacement '1'->'l' (+0.250)",
    "top_shap_3": "Suspicious Sub-label (+0.120)",
    "analyst_summary": "Financial credential theft lure; lookalike character evasion against anti-phishing filters."
  },
  "app1e-support-id.top": {
    "domain": "app1e-support-id.top",
    "attack_vector": "typosquatting",
    "threat_actor": "Smishing Operator",
    "malware_family": "AppleID-Stealer",
    "expected_verdict": "BLOCK",
    "risk_score": 89,
    "entropy": 3.44,
    "consonant_ratio": 1.67,
    "digit_ratio": 0.05,
    "subdomain_depth": 1,
    "tld_reputation": 0.85,
    "mitre_technique": "T1566.002",
    "dns_query_type": "A",
    "top_shap_1": "Brand Target 'apple' (+0.320)",
    "top_shap_2": "Suspicious TLD '.top' (+0.280)",
    "top_shap_3": "Character Replacement '1'->'l' (+0.190)",
    "analyst_summary": "High-confidence phishing campaign targeting Apple ID credentials on disposable .top TLD."
  },
  "arnazon-orders.net": {
    "domain": "arnazon-orders.net",
    "attack_vector": "typosquatting",
    "threat_actor": "Scam Coalition",
    "malware_family": "E-Commerce Phish",
    "expected_verdict": "FLAG",
    "risk_score": 76,
    "entropy": 3.31,
    "consonant_ratio": 1.67,
    "digit_ratio": 0.0,
    "subdomain_depth": 1,
    "tld_reputation": 0.3,
    "mitre_technique": "T1566.002",
    "dns_query_type": "A",
    "top_shap_1": "Homoglyph 'rn'->'m' (+0.330)",
    "top_shap_2": "Brand Target 'amazon' (+0.270)",
    "top_shap_3": "E-Commerce Lure (+0.110)",
    "analyst_summary": "Order spoofing lure targeting Amazon customers; Latin confusable 'rn' sequence."
  },
  "micros0ft-login.com": {
    "domain": "micros0ft-login.com",
    "attack_vector": "typosquatting",
    "threat_actor": "Storm-0558 Phishing",
    "malware_family": "M365 Lure",
    "expected_verdict": "FLAG",
    "risk_score": 81,
    "entropy": 3.68,
    "consonant_ratio": 2.2,
    "digit_ratio": 0.05,
    "subdomain_depth": 1,
    "tld_reputation": 0.1,
    "mitre_technique": "T1566.002",
    "dns_query_type": "A",
    "top_shap_1": "Numeral Substitution '0'->'o' (+0.320)",
    "top_shap_2": "Brand Target 'microsoft' (+0.290)",
    "top_shap_3": "Login Keyword (+0.110)",
    "analyst_summary": "Enterprise credential phish mimicking M365 authentication screen."
  },
  "offic365-security.com": {
    "domain": "offic365-security.com",
    "attack_vector": "typosquatting",
    "threat_actor": "M365 Harvester",
    "malware_family": "PhishKit-365",
    "expected_verdict": "FLAG",
    "risk_score": 83,
    "entropy": 3.88,
    "consonant_ratio": 1.67,
    "digit_ratio": 0.14,
    "subdomain_depth": 1,
    "tld_reputation": 0.1,
    "mitre_technique": "T1566.002",
    "dns_query_type": "A",
    "top_shap_1": "Brand Target 'office365' (+0.350)",
    "top_shap_2": "Numeral Leetspeak '3'->'e' (+0.260)",
    "top_shap_3": "Security Keyword (+0.120)",
    "analyst_summary": "Sophisticated corporate phishing lure; target employee credential interception."
  },
  "faceb00k-security.top": {
    "domain": "faceb00k-security.top",
    "attack_vector": "typosquatting",
    "threat_actor": "Social Credential Theft",
    "malware_family": "FB-Phish",
    "expected_verdict": "BLOCK",
    "risk_score": 88,
    "entropy": 4.01,
    "consonant_ratio": 1.83,
    "digit_ratio": 0.1,
    "subdomain_depth": 1,
    "tld_reputation": 0.85,
    "mitre_technique": "T1566.002",
    "dns_query_type": "A",
    "top_shap_1": "Brand Target 'facebook' (+0.340)",
    "top_shap_2": "Numeral '00' (+0.250)",
    "top_shap_3": "High-Risk TLD '.top' (+0.220)",
    "analyst_summary": "Social media account takeover lure hosted on abuse-heavy registrar."
  },
  "netf1ix-billing.info": {
    "domain": "netf1ix-billing.info",
    "attack_vector": "typosquatting",
    "threat_actor": "Subscription Scam",
    "malware_family": "BillingPhish",
    "expected_verdict": "FLAG",
    "risk_score": 79,
    "entropy": 3.48,
    "consonant_ratio": 1.83,
    "digit_ratio": 0.05,
    "subdomain_depth": 1,
    "tld_reputation": 0.6,
    "mitre_technique": "T1566.002",
    "dns_query_type": "A",
    "top_shap_1": "Brand Target 'netflix' (+0.330)",
    "top_shap_2": "Character '1'->'l' (+0.240)",
    "top_shap_3": "Billing Keyword (+0.120)",
    "analyst_summary": "Credit card harvesting lure imitating streaming service payment failure notification."
  },
  "goog1e-auth.net": {
    "domain": "goog1e-auth.net",
    "attack_vector": "typosquatting",
    "threat_actor": "Credential Harvester",
    "malware_family": "Google-OAuth-Fake",
    "expected_verdict": "FLAG",
    "risk_score": 80,
    "entropy": 3.37,
    "consonant_ratio": 1.0,
    "digit_ratio": 0.07,
    "subdomain_depth": 1,
    "tld_reputation": 0.2,
    "mitre_technique": "T1566.002",
    "dns_query_type": "A",
    "top_shap_1": "Character '1'->'l' (+0.340)",
    "top_shap_2": "Brand Target 'google' (+0.300)",
    "top_shap_3": "Auth Keyword (+0.120)",
    "analyst_summary": "Deceptive OAuth login screen mimicking Google Workspace sign-in flow."
  },
  "chasee-online-login.info": {
    "domain": "chasee-online-login.info",
    "attack_vector": "typosquatting",
    "threat_actor": "Banking Phishing Ring",
    "malware_family": "ChasePhish",
    "expected_verdict": "FLAG",
    "risk_score": 82,
    "entropy": 3.49,
    "consonant_ratio": 1.1,
    "digit_ratio": 0.0,
    "subdomain_depth": 1,
    "tld_reputation": 0.6,
    "mitre_technique": "T1566.002",
    "dns_query_type": "A",
    "top_shap_1": "Double Letter Typosquat 'ee' (+0.310)",
    "top_shap_2": "Brand Target 'chase' (+0.280)",
    "top_shap_3": "Banking Keyword (+0.140)",
    "analyst_summary": "Consumer banking credential phishing portal with duplicate character evasion."
  },
  "wellsfarg0-auth.biz": {
    "domain": "wellsfarg0-auth.biz",
    "attack_vector": "typosquatting",
    "threat_actor": "Financial Phishing Ring",
    "malware_family": "WellsPhish",
    "expected_verdict": "FLAG",
    "risk_score": 84,
    "entropy": 4.04,
    "consonant_ratio": 2.2,
    "digit_ratio": 0.05,
    "subdomain_depth": 1,
    "tld_reputation": 0.7,
    "mitre_technique": "T1566.002",
    "dns_query_type": "A",
    "top_shap_1": "Numeral Substitution '0'->'o' (+0.330)",
    "top_shap_2": "Brand Target 'wellsfargo' (+0.290)",
    "top_shap_3": "TLD Risk (+0.150)",
    "analyst_summary": "High-confidence financial spearphishing domain targeting banking customers."
  },
  "onedrive-file-share.top": {
    "domain": "onedrive-file-share.top",
    "attack_vector": "typosquatting",
    "threat_actor": "Corporate Spearphishing",
    "malware_family": "OneDriveLure",
    "expected_verdict": "BLOCK",
    "risk_score": 87,
    "entropy": 3.83,
    "consonant_ratio": 1.22,
    "digit_ratio": 0.0,
    "subdomain_depth": 1,
    "tld_reputation": 0.85,
    "mitre_technique": "T1566.002",
    "dns_query_type": "A",
    "top_shap_1": "Brand Target 'onedrive' (+0.320)",
    "top_shap_2": "High-Risk TLD '.top' (+0.270)",
    "top_shap_3": "File Share Keyword (+0.140)",
    "analyst_summary": "Malicious macro-enabled document delivery portal mimicking Microsoft OneDrive."
  },
  "github-verify-token.click": {
    "domain": "github-verify-token.click",
    "attack_vector": "typosquatting",
    "threat_actor": "Developer Token Theft",
    "malware_family": "GitPhish",
    "expected_verdict": "FLAG",
    "risk_score": 80,
    "entropy": 4.05,
    "consonant_ratio": 2.14,
    "digit_ratio": 0.0,
    "subdomain_depth": 1,
    "tld_reputation": 0.7,
    "mitre_technique": "T1566.002",
    "dns_query_type": "A",
    "top_shap_1": "Brand Target 'github' (+0.310)",
    "top_shap_2": "Token Theft Keyword (+0.250)",
    "top_shap_3": "TLD Risk (+0.150)",
    "analyst_summary": "Phishing site designed to harvest personal access tokens from software developers."
  },
  "slackk-workspace.cc": {
    "domain": "slackk-workspace.cc",
    "attack_vector": "typosquatting",
    "threat_actor": "Corporate Espionage",
    "malware_family": "SlackSpoof",
    "expected_verdict": "FLAG",
    "risk_score": 77,
    "entropy": 3.37,
    "consonant_ratio": 3.25,
    "digit_ratio": 0.0,
    "subdomain_depth": 1,
    "tld_reputation": 0.8,
    "mitre_technique": "T1566.002",
    "dns_query_type": "A",
    "top_shap_1": "Double Character 'kk' (+0.300)",
    "top_shap_2": "Brand Target 'slack' (+0.280)",
    "top_shap_3": "Abusive TLD (+0.140)",
    "analyst_summary": "Fake Slack enterprise login portal targeting internal corporate communications."
  },
  "ywjjzdeymzq1ng==.attacker-c2.net": {
    "domain": "YWJjZDEyMzQ1Ng==.attacker-c2.net",
    "attack_vector": "tunneling",
    "threat_actor": "Lazarus Group (Bluenoroff)",
    "malware_family": "Iodine Tunnel",
    "expected_verdict": "BLOCK",
    "risk_score": 94,
    "entropy": 4.54,
    "consonant_ratio": 5.25,
    "digit_ratio": 0.06,
    "subdomain_depth": 2,
    "tld_reputation": 0.6,
    "mitre_technique": "T1071.004",
    "dns_query_type": "TXT",
    "top_shap_1": "Base64 Subdomain Payload (+0.350)",
    "top_shap_2": "Subdomain Length 24 chars (+0.260)",
    "top_shap_3": "High Shannon Entropy 4.91 (+0.220)",
    "analyst_summary": "Iodine DNS tunnelling exfiltration; base64 payload carried in TXT/CNAME sub-labels."
  },
  "dgvzdhbhewxvywq1.c2.bad-demo.example": {
    "domain": "dGVzdHBheWxvYWQ1.c2.bad-demo.example",
    "attack_vector": "tunneling",
    "threat_actor": "Red Team Simulation",
    "malware_family": "dnscat2",
    "expected_verdict": "BLOCK",
    "risk_score": 91,
    "entropy": 4.37,
    "consonant_ratio": 3.29,
    "digit_ratio": 0.06,
    "subdomain_depth": 3,
    "tld_reputation": 0.5,
    "mitre_technique": "T1071.004",
    "dns_query_type": "CNAME",
    "top_shap_1": "Sliding Window Burst 15 QPS (+0.290)",
    "top_shap_2": "Subdomain Entropy 4.72 (+0.270)",
    "top_shap_3": "Hex/Base64 Marker (+0.190)",
    "analyst_summary": "dnscat2 encoded covert channel; repetitive high-entropy bursts in 60s window."
  },
  "hex666f6f626172.tunnel.darknet.cc": {
    "domain": "hex666f6f626172.tunnel.darknet.cc",
    "attack_vector": "tunneling",
    "threat_actor": "APT41 (Double Dragon)",
    "malware_family": "DNSExfiltrator",
    "expected_verdict": "BLOCK",
    "risk_score": 96,
    "entropy": 3.9,
    "consonant_ratio": 3.0,
    "digit_ratio": 0.3,
    "subdomain_depth": 3,
    "tld_reputation": 0.8,
    "mitre_technique": "T1071.004",
    "dns_query_type": "TXT",
    "top_shap_1": "Hexadecimal Encoded Byte Stream (+0.330)",
    "top_shap_2": "High NXDOMAIN Frequency (+0.280)",
    "top_shap_3": "Long Sub-label Length (+0.210)",
    "analyst_summary": "Covert data exfiltration channel using raw hex byte sequences encoded in subdomains."
  },
  "cgfzc3dvcmrzx2r1bxa=.covert.darknet.cc": {
    "domain": "cGFzc3dvcmRzX2R1bXA=.covert.darknet.cc",
    "attack_vector": "tunneling",
    "threat_actor": "APT28 (Fancy Bear)",
    "malware_family": "Custom UDP Tunnel",
    "expected_verdict": "BLOCK",
    "risk_score": 95,
    "entropy": 4.29,
    "consonant_ratio": 6.75,
    "digit_ratio": 0.08,
    "subdomain_depth": 3,
    "tld_reputation": 0.8,
    "mitre_technique": "T1071.004",
    "dns_query_type": "TXT",
    "top_shap_1": "Base64 Sensitive String (+0.360)",
    "top_shap_2": "Entropy Spike 4.88 (+0.250)",
    "top_shap_3": "Abnormal TXT Volume (+0.210)",
    "analyst_summary": "High-risk credential exfiltration attempt; base64 encoded credential dump in DNS query stream."
  },
  "4141414142424242.exfil-stream.pw": {
    "domain": "4141414142424242.exfil-stream.pw",
    "attack_vector": "tunneling",
    "threat_actor": "ShadowPad Operator",
    "malware_family": "ShadowPad DNS Exfil",
    "expected_verdict": "BLOCK",
    "risk_score": 97,
    "entropy": 3.62,
    "consonant_ratio": 2.25,
    "digit_ratio": 0.5,
    "subdomain_depth": 2,
    "tld_reputation": 0.85,
    "mitre_technique": "T1071.004",
    "dns_query_type": "A",
    "top_shap_1": "Raw ASCII Hex Stream (+0.340)",
    "top_shap_2": "Disposable TLD '.pw' (+0.270)",
    "top_shap_3": "Label Length 16 chars (+0.190)",
    "analyst_summary": "Enterprise exfiltration tunnel transporting structured memory artifacts via recursive queries."
  },
  "syn-chunk-4892.dnscat.io": {
    "domain": "syn-chunk-4892.dnscat.io",
    "attack_vector": "tunneling",
    "threat_actor": "dnscat2 Operator",
    "malware_family": "dnscat2-raw",
    "expected_verdict": "BLOCK",
    "risk_score": 89,
    "entropy": 4.05,
    "consonant_ratio": 3.0,
    "digit_ratio": 0.17,
    "subdomain_depth": 2,
    "tld_reputation": 0.3,
    "mitre_technique": "T1071.004",
    "dns_query_type": "CNAME",
    "top_shap_1": "dnscat Session Framing (+0.310)",
    "top_shap_2": "Sliding Window Volume (+0.240)",
    "top_shap_3": "Entropy 4.15 (+0.180)",
    "analyst_summary": "dnscat2 session synchronization handshake chunk; identified by behavioral sliding window."
  },
  "chunk01.stage2.exfil-node.ru": {
    "domain": "chunk01.stage2.exfil-node.ru",
    "attack_vector": "tunneling",
    "threat_actor": "Turla Group",
    "malware_family": "GPRS / DNS Tunnel",
    "expected_verdict": "BLOCK",
    "risk_score": 93,
    "entropy": 4.32,
    "consonant_ratio": 1.62,
    "digit_ratio": 0.11,
    "subdomain_depth": 3,
    "tld_reputation": 0.8,
    "mitre_technique": "T1071.004",
    "dns_query_type": "TXT",
    "top_shap_1": "Multi-Label Fanout (+0.320)",
    "top_shap_2": "High Volume TXT Lookup (+0.270)",
    "top_shap_3": "TLD Geographic Risk (+0.190)",
    "analyst_summary": "Structured multi-chunk file exfiltration through recursive DNS resolvers."
  },
  "chunk02.stage2.exfil-node.ru": {
    "domain": "chunk02.stage2.exfil-node.ru",
    "attack_vector": "tunneling",
    "threat_actor": "Turla Group",
    "malware_family": "GPRS / DNS Tunnel",
    "expected_verdict": "BLOCK",
    "risk_score": 93,
    "entropy": 4.25,
    "consonant_ratio": 1.62,
    "digit_ratio": 0.11,
    "subdomain_depth": 3,
    "tld_reputation": 0.8,
    "mitre_technique": "T1071.004",
    "dns_query_type": "TXT",
    "top_shap_1": "Multi-Label Fanout (+0.320)",
    "top_shap_2": "High Volume TXT Lookup (+0.270)",
    "top_shap_3": "TLD Geographic Risk (+0.190)",
    "analyst_summary": "Structured multi-chunk file exfiltration sequential packet #2."
  },
  "chunk03.stage2.exfil-node.ru": {
    "domain": "chunk03.stage2.exfil-node.ru",
    "attack_vector": "tunneling",
    "threat_actor": "Turla Group",
    "malware_family": "GPRS / DNS Tunnel",
    "expected_verdict": "BLOCK",
    "risk_score": 93,
    "entropy": 4.32,
    "consonant_ratio": 1.62,
    "digit_ratio": 0.11,
    "subdomain_depth": 3,
    "tld_reputation": 0.8,
    "mitre_technique": "T1071.004",
    "dns_query_type": "TXT",
    "top_shap_1": "Multi-Label Fanout (+0.320)",
    "top_shap_2": "High Volume TXT Lookup (+0.270)",
    "top_shap_3": "TLD Geographic Risk (+0.190)",
    "analyst_summary": "Structured multi-chunk file exfiltration sequential packet #3."
  },
  "7365637265742d6b6579.covert-dns.top": {
    "domain": "7365637265742d6b6579.covert-dns.top",
    "attack_vector": "tunneling",
    "threat_actor": "FIN8 Team",
    "malware_family": "DNSExfiltrator-v2",
    "expected_verdict": "BLOCK",
    "risk_score": 96,
    "entropy": 4.09,
    "consonant_ratio": 3.67,
    "digit_ratio": 0.51,
    "subdomain_depth": 2,
    "tld_reputation": 0.85,
    "mitre_technique": "T1071.004",
    "dns_query_type": "TXT",
    "top_shap_1": "Hex Stream Detected (+0.350)",
    "top_shap_2": "High Shannon Entropy (+0.280)",
    "top_shap_3": "TLD Risk (+0.210)",
    "analyst_summary": "Hexadecimal string representing cryptographic private key exfiltration."
  },
  "c2-beacon.dark-infra.cc": {
    "domain": "c2-beacon.dark-infra.cc",
    "attack_vector": "c2",
    "threat_actor": "APT29 (Nobelium)",
    "malware_family": "Cobalt Strike Beacon",
    "expected_verdict": "BLOCK",
    "risk_score": 98,
    "entropy": 3.62,
    "consonant_ratio": 2.0,
    "digit_ratio": 0.04,
    "subdomain_depth": 2,
    "tld_reputation": 0.9,
    "mitre_technique": "T1071.001",
    "dns_query_type": "A",
    "top_shap_1": "URLhaus Threat Feed Match (+0.450)",
    "top_shap_2": "C2 Callback Signature (+0.320)",
    "top_shap_3": "Abnormal Query Interval (+0.150)",
    "analyst_summary": "Active Cobalt Strike C2 listener; verified hit in live STIX 2.1 Threat Intel database."
  },
  "update.c2-pool.ru": {
    "domain": "update.c2-pool.ru",
    "attack_vector": "c2",
    "threat_actor": "Lazarus Group (APT38)",
    "malware_family": "Botnet Controller",
    "expected_verdict": "BLOCK",
    "risk_score": 96,
    "entropy": 3.62,
    "consonant_ratio": 1.17,
    "digit_ratio": 0.06,
    "subdomain_depth": 2,
    "tld_reputation": 0.85,
    "mitre_technique": "T1071.001",
    "dns_query_type": "A",
    "top_shap_1": "Known Botnet Controller (+0.420)",
    "top_shap_2": "Geo Anomaly Score (+0.220)",
    "top_shap_3": "High-Risk Registrar (+0.180)",
    "analyst_summary": "Malware command-and-control node; automatic active response quarantine triggered."
  },
  "cs-stage-listener.xyz": {
    "domain": "cs-stage-listener.xyz",
    "attack_vector": "c2",
    "threat_actor": "BlackCat / ALPHV",
    "malware_family": "Cobalt Strike Malleable C2",
    "expected_verdict": "BLOCK",
    "risk_score": 97,
    "entropy": 3.75,
    "consonant_ratio": 2.6,
    "digit_ratio": 0.0,
    "subdomain_depth": 1,
    "tld_reputation": 0.85,
    "mitre_technique": "T1071.001",
    "dns_query_type": "A",
    "top_shap_1": "Threat Intel Hash Match (+0.440)",
    "top_shap_2": "Malleable C2 Profile (+0.290)",
    "top_shap_3": "Disposable TLD (+0.160)",
    "analyst_summary": "Cobalt Strike malleable C2 profile listener staging point for lateral network movement."
  },
  "flux-node-881.dynamic-dns.pw": {
    "domain": "flux-node-881.dynamic-dns.pw",
    "attack_vector": "c2",
    "threat_actor": "Storm-0978",
    "malware_family": "Fast-Flux Botnet",
    "expected_verdict": "BLOCK",
    "risk_score": 95,
    "entropy": 4.16,
    "consonant_ratio": 3.0,
    "digit_ratio": 0.11,
    "subdomain_depth": 2,
    "tld_reputation": 0.85,
    "mitre_technique": "T1583.001",
    "dns_query_type": "A",
    "top_shap_1": "Fast-Flux DNS Shuffling (+0.380)",
    "top_shap_2": "Rapid TTL Decay 60s (+0.260)",
    "top_shap_3": "High IP Churn Rate (+0.210)",
    "analyst_summary": "Fast-flux botnet domain rapidly rotating through compromised residential IP proxies."
  },
  "beacon.apt29-relay.ru": {
    "domain": "beacon.apt29-relay.ru",
    "attack_vector": "c2",
    "threat_actor": "Cozy Bear (APT29)",
    "malware_family": "WellMess C2",
    "expected_verdict": "BLOCK",
    "risk_score": 98,
    "entropy": 3.88,
    "consonant_ratio": 1.29,
    "digit_ratio": 0.1,
    "subdomain_depth": 2,
    "tld_reputation": 0.85,
    "mitre_technique": "T1071.001",
    "dns_query_type": "A",
    "top_shap_1": "Known State-Sponsored C2 (+0.460)",
    "top_shap_2": "STIX 2.1 IOC Indicator (+0.340)",
    "top_shap_3": "Geographic Risk (+0.170)",
    "analyst_summary": "Nation-state cyber espionage command relay node with verified IOC signature."
  },
  "teamserver.redteam-test.top": {
    "domain": "teamserver.redteam-test.top",
    "attack_vector": "c2",
    "threat_actor": "Red Team Staging",
    "malware_family": "Sliver C2",
    "expected_verdict": "BLOCK",
    "risk_score": 93,
    "entropy": 3.28,
    "consonant_ratio": 1.67,
    "digit_ratio": 0.0,
    "subdomain_depth": 2,
    "tld_reputation": 0.85,
    "mitre_technique": "T1071.001",
    "dns_query_type": "A",
    "top_shap_1": "C2 Framework Indicator (+0.360)",
    "top_shap_2": "TLD Risk (+0.240)",
    "top_shap_3": "Zero Whitelist Prior (+0.180)",
    "analyst_summary": "Sliver C2 teamserver staging endpoint for multi-operator red team campaigns."
  },
  "deaddrop-resolver.ru": {
    "domain": "deaddrop-resolver.ru",
    "attack_vector": "c2",
    "threat_actor": "Sandworm / GRU",
    "malware_family": "BlackEnergy C2",
    "expected_verdict": "BLOCK",
    "risk_score": 97,
    "entropy": 3.35,
    "consonant_ratio": 1.57,
    "digit_ratio": 0.0,
    "subdomain_depth": 1,
    "tld_reputation": 0.85,
    "mitre_technique": "T1071.001",
    "dns_query_type": "TXT",
    "top_shap_1": "Dead-Drop Resolver Technique (+0.410)",
    "top_shap_2": "Encrypted TXT Record Response (+0.310)",
    "top_shap_3": "Threat Intel (+0.190)",
    "analyst_summary": "Dead-drop DNS resolving channel where compromised hosts receive encrypted command payloads in TXT responses."
  }
};

export function lookupThreatCorpus(domain: string): ThreatCorpusEntry | null {
  if (!domain) return null;
  const clean = domain.trim().toLowerCase();
  if (THREAT_CORPUS[clean]) return THREAT_CORPUS[clean];
  // Subdomain suffix match
  for (const [key, entry] of Object.entries(THREAT_CORPUS)) {
    if (clean.endsWith('.' + key) || key.endsWith('.' + clean)) {
      return entry;
    }
  }
  return null;
}
